import * as functions from 'firebase-functions/v1';
import * as admin from 'firebase-admin';
import sharp from 'sharp';

/**
 * Ensure a 1:1 square crop exists for an image
 * If it doesn't exist, generate it from the original and save to Firebase Storage
 * 
 * @param featuredImage - The featured image object from Firestore
 * @param contentCollection - 'blog_posts' or 'listings'
 * @param contentId - Document ID
 * @returns URL of the 1:1 crop (existing or newly generated)
 */
export async function ensureSquareCrop(
  featuredImage: any,
  contentCollection: string,
  contentId: string
): Promise<string> {
  // Check if 1:1 crop already exists (prefer og size for Instagram)
  if (featuredImage?.crops?.['1:1']?.og) {
    functions.logger.info('Using existing 1:1 og crop', { contentId });
    return featuredImage.crops['1:1'].og;
  }
  
  if (featuredImage?.crops?.['1:1']?.full) {
    functions.logger.info('Using existing 1:1 full crop', { contentId });
    return featuredImage.crops['1:1'].full;
  }
  
  // If no 1:1 crop exists, generate from original
  const originalUrl = featuredImage?.url;
  if (!originalUrl) {
    throw new Error('No original image URL available for auto-crop');
  }
  
  functions.logger.info('Generating 1:1 crop from original', { 
    contentId, 
    originalUrl: originalUrl.substring(0, 100) 
  });
  
  try {
    // Fetch original image
    const response = await fetch(originalUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch original image: ${response.status}`);
    }
    
    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    // Get image dimensions
    const metadata = await sharp(buffer).metadata();
    const width = metadata.width || 0;
    const height = metadata.height || 0;
    
    if (width === 0 || height === 0) {
      throw new Error('Invalid image dimensions');
    }
    
    functions.logger.info('Original image dimensions', { 
      contentId, 
      width, 
      height 
    });
    
    // Calculate center square crop
    const size = Math.min(width, height);
    const left = Math.floor((width - size) / 2);
    const top = Math.floor((height - size) / 2);
    
    // Generate 1:1 crop at 1200px (og size for social media)
    const croppedBuffer = await sharp(buffer)
      .rotate() // Auto-rotate based on EXIF
      .extract({ left, top, width: size, height: size })
      .resize(1200, 1200, { 
        fit: 'inside', 
        withoutEnlargement: false 
      })
      .jpeg({ 
        quality: 85, 
        progressive: true, 
        mozjpeg: true 
      })
      .toBuffer();
    
    functions.logger.info('Generated 1:1 crop', { 
      contentId, 
      size: croppedBuffer.length 
    });
    
    // Save to Firebase Storage
    const bucket = admin.storage().bucket();
    const path = `${contentCollection}/${contentId}/1-1-og.jpg`;
    const file = bucket.file(path);
    
    // Generate download token
    const crypto = await import('crypto');
    const downloadToken = crypto.randomBytes(32).toString('hex');
    
    await file.save(croppedBuffer, {
      metadata: {
        contentType: 'image/jpeg',
        metadata: {
          aspectRatio: '1:1',
          size: 'og',
          autoGenerated: 'true',
          firebaseStorageDownloadTokens: downloadToken,
        },
      },
    });
    
    // Construct public URL
    const imageUrl = `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(path)}?alt=media&token=${downloadToken}`;
    
    functions.logger.info('Auto-generated 1:1 crop saved to Storage', { 
      contentId, 
      path,
      url: imageUrl.substring(0, 100)
    });
    
    // Update Firestore with new crop
    const db = admin.firestore();
    await db.collection(contentCollection).doc(contentId).update({
      'featuredImage.crops.1:1.og': imageUrl,
    });
    
    functions.logger.info('Firestore updated with auto-generated crop', { contentId });
    
    return imageUrl;
    
  } catch (error: any) {
    functions.logger.error('Failed to generate 1:1 crop', {
      contentId,
      error: error?.message,
      stack: error?.stack?.substring(0, 500),
    });
    throw new Error(`auto_crop_failed: ${error?.message}`);
  }
}
